const Menu = [
    {
    id: 1,
    image: 'images/maggie.png',
    name: 'Maggie',
    category: 'lunch',
    price: 30,
    description: 'lorem ispum',
    },
    {
        id: 2,
        image: 'images/idli.jpg',
        name: 'Idli',
        category: 'breakfast',
        price: 50,
        description: 'lorem ispum',
    },
    {
        id: 3,
        image: 'images/alooParatha.jpg',
        name: 'Aloo Paratha',
        category: 'breakfast',
        price: 20,
        description: 'lorem ispum',
    },
    {
        id: 4,
        image: 'images/chole.jpg',
        name: 'Chole Bhature',
        category: 'lunch',
        price: 50,
        description: 'lorem ispum',
    },
    {
        id: 5,
        image: 'images/gulabJamun.jfif',
        name: 'Gulab Jamun',
        category: 'desert',
        price: 50,
        description: 'lorem ispum',
    },
    {
        id: 6,
        image: 'images/MurabadiChickenBiryani.jpg',
        name: 'Muradabadi Chicken Biryani',
        category: 'dinner',
        price: 200,
        description: 'sexy biryani',
    },
    {
        id: 7,
        image: 'images/pulao.jpg',
        name: 'Pulao',
        category: 'breakfast',
        price: 50,
        description: 'lorem ispum',
    },
    {
        id: 8,
        image: 'images/normalThali.jpg',
        name: 'Veg Normal Thali',
        category: 'lunch',
        price: 70,
        description: 'lorem ispum',
    },
    {
        id: 9,
        image: 'images/sabjiPoori.jpg',
        name: 'Sabji Poori',
        category: 'dinner',
        price: 60,
        description: 'lorem ispum',
    },
    {
        id: 10,
        image: 'images/iceCream.jpg',
        name: 'Vanilla Ice-Cream',
        category: 'desert',
        price: 50,
        description: 'lorem ispum',
    },
    {
        id: 11,
        image: 'images/cololateCake.jpg',
        name: 'Chocolate Cake',
        category: 'desert',
        price: 100,
        description: '3 cups all-purpose flour',
    },
    
];

export default Menu;